version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  lint:
    docker:
      # Use the same Docker base as the project
      - image: ubuntu

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get update
            apt-get install wget -y
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
            apt-get install tidy -y
      - run:
          name: Lint index.html
          command: |
            tidy -q -e *.html

      # run lint!
      - run:
          name: run lint
          command: hadolint --ignore DL3006 Dockerfile

  build_docker_image:
    machine: true
    steps:
      - checkout
      - run:
          name: Build Docker image
          command: |
            docker build -t ankurprasad711/myfirstapp .
            echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker push ankurprasad711/myfirstapp


  add_kubectl:
    docker:
    - image: amazon/aws-cli
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Update Kubeconfiguration eks
          command: aws eks --region us-west-2 update-kubeconfig --name capstone
      - run:
          name: blue service 
          command: |
            kubectl apply -f ./files/blue.json        
      - run:
          name: green Service 
          command: |       
            kubectl apply -f ./files/green.json
      - run:
          name: Redirect to Blue 
          command: |       
            kubectl apply -f ./files/Blue-Service.json
  
  approval_and_apply_green:
    docker:
    - image: amazon/aws-cli
    steps:
      - checkout
      - kubernetes/install-kubectl
      - run:
          name: Update Kubeconfiguration eks
          command: aws eks --region us-west-2 update-kubeconfig --name capstone

      - run:
          name: Redirect to Green
          command: |
            kubectl apply -f ./files/Green-Service.json

workflows:
  default:
    jobs:
      - lint
      - build_docker_image:
          requires: [lint]
      - add_kubectl:
          requires: [build_docker_image]
      - green_approval:
          type: approval
          requires: [add_kubectl]
      - approval_and_apply_green:
          requires: [green_approval]
