version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  lint:
    docker:
      # Use the same Docker base as the project
      - image: ubuntu

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            apt-get update
            apt-get install wget -y
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 && chmod +x /bin/hadolint
            apt-get install tidy -y
      - run:
          name: Lint index.html
          command: |
            tidy -q -e *.html

      # run lint!
      - run:
          name: run lint
          command: hadolint --ignore DL3006 Dockerfile

workflows:
  default:
    jobs:
      - lint
