version: 2.1

orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  lint:
    docker:
      # Use the same Docker base as the project
      - image: ubuntu

    working_directory: ~/repo

    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            make install
      
      - run:
          name: Lint index.html
          command: |
            tidy -q -e *.html

      # run lint!
      - run:
          name: run lint
          command: make lint

workflows:
  default:
    jobs:
      - lint
